export const questions = ({quiz}) => quiz.questions;
export const results = ({quiz}) => quiz.results;
export const index = ({quiz}) => quiz.index;
export const score = ({quiz}) => quiz.score;
export const name = ({quiz}) => quiz.name;
export const selected = ({quiz}) => quiz.selected;
export const total = ({quiz}) => quiz.total;
export const show = ({quiz}) => quiz.show;
export const isCorrect = ({quiz}) => quiz.isCorrect;
